#!/bin/bash

ACOMPC="/Users/apple/Desktop/air_20/bin/acompc"
ADT="/Users/apple/Desktop/air_20/bin/adt"
VERSION="FWVideoEncoder/2.6"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

SWFVERSION=31

NAME="FWEncoderANE"

echo "Generating SWC"
$ACOMPC -include-classes -source-path="AS3/" -include-sources "AS3/com/" -include-sources "AS3/cc/" -swf-version=$SWFVERSION -target-player=20 -define+=CONFIG::DEMO,false -define+=CONFIG::AIR,true -define+=CONFIG::FLASCC,false -define+=CONFIG::CODECS,"''" -output $NAME.swc
sleep 3

cp $NAME.swc Apple/iOS/ane/$NAME.swc
echo "GENERATING LIBRARY from SWC"
unzip -q -o $NAME.swc -d Apple/iOS/Release
sleep 2
[[ -f "catalog.xml" ]] && rm -f "catalog.xml"

cp Apple/iOS/Release/library.swf ../releases/$VERSION/lib/iOS/Release/library.swf

echo "GENERATING ANE"
$ADT -package -target ane Apple/iOS/ane/$NAME.ane $DIR/Apple/iOS/extension.xml -swc $NAME.swc -platform iPhone-ARM -C Apple/iOS/Release library.swf lib$NAME.a -platformoptions Apple/iOS/platform.xml
sleep 2
[[ -f "library.swf" ]] && rm -f "library.swf"

rm *.swc

echo "DONE!"
